name: components
recipe: pantheon
config:
  framework: drupal8

services:
  appserver:
    run_as_root:
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt-get install -y nodejs
      - npm install -g grunt grunt-cli

tooling:
  npm:
    service: appserver
    cmd: cd /app/web/themes/gesso && npm
  grunt:
    service: appserver
    cmd: cd /app/web/themes/gesso && grunt
